[package]
name = "nip_01"
version = "1.0.0"
authors = ["ZHANG, HENGMING"]

[addresses]
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
nip_01_addr = "_"

[dev-addresses]
nip_01_addr = "0x111"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
